/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.server.test;

import java.io.IOException;
import java.util.Scanner;

public class App {
    public static Scanner sc = new Scanner(System.in);
    public static String ip = null;
    public static boolean amIConnect = false;

    public static void main(String[] args) throws IOException {
        System.out.print("Enter Server Port : ");
        int port = sc.nextInt();
        Server.makePort(port);
        while (true) {
            String command = sc.next();
            while (!command.equals("conn") && !amIConnect) {
                System.out.println("Can't Send without available client !!!");
                command = sc.nextLine();
                if (command.equals("conn")) {
                    System.out.println("reach");
                    amIConnect = true;
                    break;
                }
            }
            if (command.equals("conn")) {
                if (amIConnect) {
                    Client.Close();
                }
                amIConnect = true;
                ip = sc.next();
                port = sc.nextInt();
                Client.setupClient(ip, port);
                Server.setupServer();
                Client.iniVar();
                Server.iniBuffers();
                System.out.println("Accepted !");
            } else if (command.equals("send")) {
                String msg = sc.nextLine();
                Client.sendMsg(msg);
                System.out.println("Client : " + Server.bufferedReader.readLine());
            } else if (command.equals("reply")) {
                String msg = sc.nextLine();
                Server.sendMsg(msg);
                System.out.println("Server : " + Client.bufferedReader.readLine());
            } else if (command.equalsIgnoreCase("close")) {
                break;
            } else System.out.println("Wrong command !!");
        }
    }
}
