/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.server.test;

import org.junit.jupiter.api.Test;

import java.io.IOException;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void clientSend() {
        assertAll(
                () -> assertTrue(Testwork.testOpenPort("localhost", 8833)),
                () -> assertTrue(Testwork.testSend("hello world")),
                () -> assertTrue(Testwork.testReply("finally done")),
                () -> assertTrue(Testwork.addNewClient("localhost", 8833))
        );
    }
}
