/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.server.test;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void clientSend() {

    }

    void serverReply() {

    }

    void clientRec() {

    }

    void serverRec() {

    }
}
